# --------- Building stage ---------
FROM golang:1.24-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o server ./apps/server/cmd/

# --------- Final image ---------
FROM alpine:3.21

WORKDIR /app

RUN apk add --no-cache ca-certificates

COPY --from=builder /app/server .

CMD ["./server"]