# --------- Stage 1: Build proto Go files ---------
FROM golang:1.24-alpine AS proto-go

RUN apk add --no-cache protobuf protobuf-dev bash findutils

WORKDIR /src

COPY 01-proto ./01-proto

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6

ENV PROTOC_INCLUDE=/usr/include

RUN mkdir -p /proto-go-out

RUN find 01-proto -name "*.proto" | xargs protoc \
    --proto_path=. \
    --proto_path="$GOPATH/pkg/mod" \
    --proto_path="$PROTOC_INCLUDE" \
    --go_out=/proto-go-out \
    --go_opt=module=shvdg/crazed-conquerer

# --------- Stage 2: Build proto Dart files ---------
FROM dart:3.8-sdk as proto-dart

RUN apt-get update && apt-get install -y protobuf-compiler findutils

WORKDIR /src

COPY 01-proto ./01-proto

RUN dart pub global activate protoc_plugin
ENV PATH="$PATH:/root/.pub-cache/bin"

RUN mkdir -p /proto-dart-out

RUN find /usr/include/google/protobuf -name "*.proto" > google_wkt.txt

RUN find 01-proto -name "*.proto" | xargs protoc \
    --proto_path=. \
    --proto_path=/usr/include \
    --dart_out=/proto-dart-out \
    $(cat google_wkt.txt)

# --------- Stage 3: Export artifacts ---------
FROM alpine:3.21

WORKDIR /artifacts

COPY --from=proto-go /proto-go-out ./go/
COPY --from=proto-dart /proto-dart-out ./dart/